"""
Direct the client to resolve this field locally, either from the cache or local resolvers.
"""
directive @client(
  """
  When true, the client will never use the cache for this value. See
  https://www.apollographql.com/docs/react/essentials/local-state/#forcing-resolvers-with-clientalways-true
  """
  always: Boolean
) on FIELD | FRAGMENT_DEFINITION | INLINE_FRAGMENT

"""
Export this locally resolved field as a variable to be used in the remainder of this query. See
https://www.apollographql.com/docs/react/essentials/local-state/#using-client-fields-as-variables
"""
directive @export(
  """The variable name to export this field as."""
  as: String!
) on FIELD

"""
Specify a custom store key for this result. See
https://www.apollographql.com/docs/react/advanced/caching/#the-connection-directive
"""
directive @connection(
  """Specify the store key."""
  key: String!

  """
  An array of query argument names to include in the generated custom store key.
  """
  filter: [String!]
) on FIELD

type Query {
  """Fetches an object given its ID"""
  node(
    """The ID of an object"""
    id: ID!
  ): Node
  postsConnection(after: String, first: Int, before: String, last: Int): PostItemConnection!
  posts(limit: Int!, offset: Int!): PostsPaginated!
  allPosts: [PostItem!]!
}

"""An object with an ID"""
interface Node {
  """The id of the object."""
  id: ID!
}

"""A connection to a list of items."""
type PostItemConnection {
  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """A list of edges."""
  edges: [PostItemEdge]
}

"""Information about pagination in a connection."""
type PageInfo {
  """When paginating forwards, are there more items?"""
  hasNextPage: Boolean!

  """When paginating backwards, are there more items?"""
  hasPreviousPage: Boolean!

  """When paginating backwards, the cursor to continue."""
  startCursor: String

  """When paginating forwards, the cursor to continue."""
  endCursor: String
}

"""An edge in a connection."""
type PostItemEdge {
  """The item at the end of the edge"""
  node: PostItem

  """A cursor for use in pagination"""
  cursor: String!
}

type PostItem implements Node {
  """The ID of an object"""
  id: ID!
  dbId: ID!
  title: String!
  body: String!
}

type PostsPaginated {
  total: Int!
  hasNextPage: Boolean!
  results: [PostItem!]!
}

type Mutation {
  addPostItem(input: AddPostItemInput!): AddPostItemPayload
  updatePostItem(input: UpdatePostItemInput!): UpdatePostItemPayload
  deletePostItem(input: DeletePostItemInput!): DeletePostItemPayload
}

input AddPostItemInput {
  title: String!
  body: String!
  clientMutationId: String
}

type AddPostItemPayload {
  addedPostItem: PostItem
  addedPostItemEdge: PostItemEdge
  clientMutationId: String
}

input UpdatePostItemInput {
  id: ID!
  title: String!
  body: String!
  clientMutationId: String
}

type UpdatePostItemPayload {
  updatedPostItem: PostItem
  clientMutationId: String
}

input DeletePostItemInput {
  id: ID!
  clientMutationId: String
}

type DeletePostItemPayload {
  deletedPostItemId: ID
  clientMutationId: String
}
