// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");
var ReactTestingLibrary = require("../../bindings/ReactTestingLibrary/ReactTestingLibrary.bs.js");

var Runner = Jest.Runner;

var test = Jest.test;

var testAsync = Jest.testAsync;

var testPromise = Jest.testPromise;

var testAll = Jest.testAll;

var describe = Jest.describe;

var beforeAllAsync = Jest.beforeAllAsync;

var beforeAllPromise = Jest.beforeAllPromise;

var beforeEachAsync = Jest.beforeEachAsync;

var beforeEachPromise = Jest.beforeEachPromise;

var afterAllAsync = Jest.afterAllAsync;

var afterAllPromise = Jest.afterAllPromise;

var afterEachAsync = Jest.afterEachAsync;

var afterEachPromise = Jest.afterEachPromise;

var Only = Jest.Only;

var Skip = Jest.Skip;

var Todo = Jest.Todo;

var pass = Jest.pass;

var fail = Jest.fail;

var Expect = Jest.Expect;

var ExpectJs = Jest.ExpectJs;

var MockJs = Jest.MockJs;

var Jest$1 = Jest.Jest;

var JestJs = Jest.JestJs;

var expect = Jest.Expect.expect;

var expectFn = Jest.Expect.expectFn;

var toBe = Jest.Expect.toBe;

var toBeCloseTo = Jest.Expect.toBeCloseTo;

var toBeSoCloseTo = Jest.Expect.toBeSoCloseTo;

var toBeGreaterThan = Jest.Expect.toBeGreaterThan;

var toBeGreaterThanOrEqual = Jest.Expect.toBeGreaterThanOrEqual;

var toBeLessThan = Jest.Expect.toBeLessThan;

var toBeLessThanOrEqual = Jest.Expect.toBeLessThanOrEqual;

var toBeSupersetOf = Jest.Expect.toBeSupersetOf;

var toContain = Jest.Expect.toContain;

var toContainEqual = Jest.Expect.toContainEqual;

var toContainString = Jest.Expect.toContainString;

var toEqual = Jest.Expect.toEqual;

var toHaveLength = Jest.Expect.toHaveLength;

var toMatch = Jest.Expect.toMatch;

var toMatchInlineSnapshot = Jest.Expect.toMatchInlineSnapshot;

var toMatchRe = Jest.Expect.toMatchRe;

var toMatchSnapshot = Jest.Expect.toMatchSnapshot;

var toMatchSnapshotWithName = Jest.Expect.toMatchSnapshotWithName;

var toThrow = Jest.Expect.toThrow;

var toThrowErrorMatchingSnapshot = Jest.Expect.toThrowErrorMatchingSnapshot;

var not_ = Jest.Expect.not_;

var not__ = Jest.Expect.not__;

var Operators = Jest.Expect.Operators;

var FireEvent = ReactTestingLibrary.FireEvent;

var act = ReactTestingLibrary.act;

var getByLabelText = ReactTestingLibrary.getByLabelText;

var getAllByLabelText = ReactTestingLibrary.getAllByLabelText;

var queryByLabelText = ReactTestingLibrary.queryByLabelText;

var queryAllByLabelText = ReactTestingLibrary.queryAllByLabelText;

var findByLabelText = ReactTestingLibrary.findByLabelText;

var findAllByLabelText = ReactTestingLibrary.findAllByLabelText;

var getByPlaceholderText = ReactTestingLibrary.getByPlaceholderText;

var getAllByPlaceholderText = ReactTestingLibrary.getAllByPlaceholderText;

var queryByPlaceholderText = ReactTestingLibrary.queryByPlaceholderText;

var queryAllByPlaceholderText = ReactTestingLibrary.queryAllByPlaceholderText;

var findByPlaceholderText = ReactTestingLibrary.findByPlaceholderText;

var findAllByPlaceholderText = ReactTestingLibrary.findAllByPlaceholderText;

var getByText = ReactTestingLibrary.getByText;

var getAllByText = ReactTestingLibrary.getAllByText;

var queryByText = ReactTestingLibrary.queryByText;

var queryAllByText = ReactTestingLibrary.queryAllByText;

var findByText = ReactTestingLibrary.findByText;

var findAllByText = ReactTestingLibrary.findAllByText;

var getByAltText = ReactTestingLibrary.getByAltText;

var getAllByAltText = ReactTestingLibrary.getAllByAltText;

var queryByAltText = ReactTestingLibrary.queryByAltText;

var queryAllByAltText = ReactTestingLibrary.queryAllByAltText;

var findByAltText = ReactTestingLibrary.findByAltText;

var findAllByAltText = ReactTestingLibrary.findAllByAltText;

var getByTitle = ReactTestingLibrary.getByTitle;

var getAllByTitle = ReactTestingLibrary.getAllByTitle;

var queryByTitle = ReactTestingLibrary.queryByTitle;

var queryAllByTitle = ReactTestingLibrary.queryAllByTitle;

var findByTitle = ReactTestingLibrary.findByTitle;

var findAllByTitle = ReactTestingLibrary.findAllByTitle;

var getByDisplayValue = ReactTestingLibrary.getByDisplayValue;

var getAllByDisplayValue = ReactTestingLibrary.getAllByDisplayValue;

var queryByDisplayValue = ReactTestingLibrary.queryByDisplayValue;

var queryAllByDisplayValue = ReactTestingLibrary.queryAllByDisplayValue;

var findByDisplayValue = ReactTestingLibrary.findByDisplayValue;

var findAllByDisplayValue = ReactTestingLibrary.findAllByDisplayValue;

var getByRole = ReactTestingLibrary.getByRole;

var getAllByRole = ReactTestingLibrary.getAllByRole;

var queryByRole = ReactTestingLibrary.queryByRole;

var queryAllByRole = ReactTestingLibrary.queryAllByRole;

var findByRole = ReactTestingLibrary.findByRole;

var findAllByRole = ReactTestingLibrary.findAllByRole;

var getByTestId = ReactTestingLibrary.getByTestId;

var getAllByTestId = ReactTestingLibrary.getAllByTestId;

var queryByTestId = ReactTestingLibrary.queryByTestId;

var queryAllByTestId = ReactTestingLibrary.queryAllByTestId;

var findByTestId = ReactTestingLibrary.findByTestId;

var findAllByTestId = ReactTestingLibrary.findAllByTestId;

var render = ReactTestingLibrary.render;

var debug = ReactTestingLibrary.debug;

exports.Runner = Runner;
exports.test = test;
exports.testAsync = testAsync;
exports.testPromise = testPromise;
exports.testAll = testAll;
exports.describe = describe;
exports.beforeAllAsync = beforeAllAsync;
exports.beforeAllPromise = beforeAllPromise;
exports.beforeEachAsync = beforeEachAsync;
exports.beforeEachPromise = beforeEachPromise;
exports.afterAllAsync = afterAllAsync;
exports.afterAllPromise = afterAllPromise;
exports.afterEachAsync = afterEachAsync;
exports.afterEachPromise = afterEachPromise;
exports.Only = Only;
exports.Skip = Skip;
exports.Todo = Todo;
exports.pass = pass;
exports.fail = fail;
exports.Expect = Expect;
exports.ExpectJs = ExpectJs;
exports.MockJs = MockJs;
exports.Jest = Jest$1;
exports.JestJs = JestJs;
exports.expect = expect;
exports.expectFn = expectFn;
exports.toBe = toBe;
exports.toBeCloseTo = toBeCloseTo;
exports.toBeSoCloseTo = toBeSoCloseTo;
exports.toBeGreaterThan = toBeGreaterThan;
exports.toBeGreaterThanOrEqual = toBeGreaterThanOrEqual;
exports.toBeLessThan = toBeLessThan;
exports.toBeLessThanOrEqual = toBeLessThanOrEqual;
exports.toBeSupersetOf = toBeSupersetOf;
exports.toContain = toContain;
exports.toContainEqual = toContainEqual;
exports.toContainString = toContainString;
exports.toEqual = toEqual;
exports.toHaveLength = toHaveLength;
exports.toMatch = toMatch;
exports.toMatchInlineSnapshot = toMatchInlineSnapshot;
exports.toMatchRe = toMatchRe;
exports.toMatchSnapshot = toMatchSnapshot;
exports.toMatchSnapshotWithName = toMatchSnapshotWithName;
exports.toThrow = toThrow;
exports.toThrowErrorMatchingSnapshot = toThrowErrorMatchingSnapshot;
exports.not_ = not_;
exports.not__ = not__;
exports.Operators = Operators;
exports.FireEvent = FireEvent;
exports.act = act;
exports.getByLabelText = getByLabelText;
exports.getAllByLabelText = getAllByLabelText;
exports.queryByLabelText = queryByLabelText;
exports.queryAllByLabelText = queryAllByLabelText;
exports.findByLabelText = findByLabelText;
exports.findAllByLabelText = findAllByLabelText;
exports.getByPlaceholderText = getByPlaceholderText;
exports.getAllByPlaceholderText = getAllByPlaceholderText;
exports.queryByPlaceholderText = queryByPlaceholderText;
exports.queryAllByPlaceholderText = queryAllByPlaceholderText;
exports.findByPlaceholderText = findByPlaceholderText;
exports.findAllByPlaceholderText = findAllByPlaceholderText;
exports.getByText = getByText;
exports.getAllByText = getAllByText;
exports.queryByText = queryByText;
exports.queryAllByText = queryAllByText;
exports.findByText = findByText;
exports.findAllByText = findAllByText;
exports.getByAltText = getByAltText;
exports.getAllByAltText = getAllByAltText;
exports.queryByAltText = queryByAltText;
exports.queryAllByAltText = queryAllByAltText;
exports.findByAltText = findByAltText;
exports.findAllByAltText = findAllByAltText;
exports.getByTitle = getByTitle;
exports.getAllByTitle = getAllByTitle;
exports.queryByTitle = queryByTitle;
exports.queryAllByTitle = queryAllByTitle;
exports.findByTitle = findByTitle;
exports.findAllByTitle = findAllByTitle;
exports.getByDisplayValue = getByDisplayValue;
exports.getAllByDisplayValue = getAllByDisplayValue;
exports.queryByDisplayValue = queryByDisplayValue;
exports.queryAllByDisplayValue = queryAllByDisplayValue;
exports.findByDisplayValue = findByDisplayValue;
exports.findAllByDisplayValue = findAllByDisplayValue;
exports.getByRole = getByRole;
exports.getAllByRole = getAllByRole;
exports.queryByRole = queryByRole;
exports.queryAllByRole = queryAllByRole;
exports.findByRole = findByRole;
exports.findAllByRole = findAllByRole;
exports.getByTestId = getByTestId;
exports.getAllByTestId = getAllByTestId;
exports.queryByTestId = queryByTestId;
exports.queryAllByTestId = queryAllByTestId;
exports.findByTestId = findByTestId;
exports.findAllByTestId = findAllByTestId;
exports.render = render;
exports.debug = debug;
/* Jest Not a pure module */
