// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fetch = require("bs-fetch/src/Fetch.bs.js");
var Js_dict = require("rescript/lib/js/js_dict.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var RescriptRelay = require("rescript-relay/src/RescriptRelay.bs.js");
var RelayRuntime = require("relay-runtime");
var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

((require('isomorphic-fetch')));

var Graphql_error = /* @__PURE__ */Caml_exceptions.create("RelayEnv.Graphql_error");

var apiUrl = "http://localhost:3000/api/graphql";

function fetchQuery(operation, variables, _cacheConfig, _uploadables) {
  return fetch(apiUrl, Fetch.RequestInit.make(/* Post */2, {
                      "content-type": "application/json",
                      accept: "application/json"
                    }, Caml_option.some(JSON.stringify(Js_dict.fromList({
                                  hd: [
                                    "query",
                                    operation.text
                                  ],
                                  tl: {
                                    hd: [
                                      "variables",
                                      variables
                                    ],
                                    tl: /* [] */0
                                  }
                                }))), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(undefined)).then(function (resp) {
              if (resp.ok) {
                return resp.json();
              } else {
                return Promise.reject({
                            RE_EXN_ID: Graphql_error,
                            _1: "Request failed: " + resp.statusText
                          });
              }
            });
}

function getRecords(environment) {
  return environment.getStore().getSource().toJSON();
}

function createEnvironment(records, param) {
  var source = new RelayRuntime.RecordSource(records !== undefined ? Caml_option.valFromOption(records) : undefined);
  var store = RescriptRelay.Store.make(source, 10, undefined, undefined);
  var network = RelayRuntime.Network.create(fetchQuery, undefined);
  return RescriptRelay.Environment.make(network, store, undefined, undefined, undefined, undefined);
}

exports.Graphql_error = Graphql_error;
exports.apiUrl = apiUrl;
exports.fetchQuery = fetchQuery;
exports.getRecords = getRecords;
exports.createEnvironment = createEnvironment;
/*  Not a pure module */
