// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Button = require("./Button.bs.js");
var Render = require("../../lib/Render/Render.bs.js");
var Storybook = require("../../bindings/Storybook/Storybook.bs.js");
var React$1 = require("@storybook/react");

function onClick($$event) {
  console.log($$event);
  
}

React$1.storiesOf("Button", Storybook.storybookModule).add("Primary", (function (param) {
            var handleClick = function ($$event) {
              console.log([
                    "onClick => ",
                    $$event
                  ]);
              
            };
            return React.createElement(Button.make, {
                        children: Render.s("Easy"),
                        onClick: handleClick
                      });
          })).add("Secondary", (function (param) {
          var handleClick = function ($$event) {
            console.log([
                  "onClick => ",
                  $$event
                ]);
            
          };
          return React.createElement(Button.make, {
                      children: Render.s("Easy"),
                      onClick: handleClick,
                      intent: "success"
                    });
        })).add("Danger", (function (param) {
        var handleClick = function ($$event) {
          console.log([
                "onClick => ",
                $$event
              ]);
          
        };
        return React.createElement(Button.make, {
                    children: Render.s("Easy"),
                    onClick: handleClick,
                    intent: "danger"
                  });
      }));

exports.onClick = onClick;
/*  Not a pure module */
