// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Theme = require("../../lib/Theme/Theme.bs.js");
var React = require("react");
var Render = require("../../lib/Render/Render.bs.js");
var AncestorCustom = require("../../lib/Theme/AncestorCustom.bs.js");

function Text$Title(Props) {
  var colorOpt = Props.color;
  var classNameOpt = Props.className;
  var tagOpt = Props.tag;
  var children = Props.children;
  var color = colorOpt !== undefined ? colorOpt : Theme.Colors.grayLight;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var tag = tagOpt !== undefined ? tagOpt : "h1";
  var titleStyles = CssJs.style([
        CssJs.color(color),
        CssJs.margin("zero"),
        CssJs.lineHeight({
              NAME: "percent",
              VAL: 80
            }),
        CssJs.fontSize(Theme.FontSize.lg)
      ]);
  return React.createElement(AncestorCustom.Config.Base.make, {
              tag: tag,
              className: titleStyles + " " + className,
              children: Render.s(children)
            });
}

var Title = {
  make: Text$Title
};

function Text$H3(Props) {
  var colorOpt = Props.color;
  var classNameOpt = Props.className;
  var tagOpt = Props.tag;
  var children = Props.children;
  var color = colorOpt !== undefined ? colorOpt : Theme.Colors.grayDark;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var tag = tagOpt !== undefined ? tagOpt : "h2";
  var titleStyles = CssJs.style([
        CssJs.color(color),
        CssJs.margin("zero"),
        CssJs.lineHeight({
              NAME: "percent",
              VAL: 90
            }),
        CssJs.fontSize(Theme.FontSize.md)
      ]);
  return React.createElement(AncestorCustom.Config.Base.make, {
              tag: tag,
              className: titleStyles + " " + className,
              children: Render.s(children)
            });
}

var H3 = {
  make: Text$H3
};

function Text$Body(Props) {
  var colorOpt = Props.color;
  var classNameOpt = Props.className;
  var tagOpt = Props.tag;
  var children = Props.children;
  var color = colorOpt !== undefined ? colorOpt : Theme.Colors.grayDark;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var tag = tagOpt !== undefined ? tagOpt : "p";
  var titleStyles = CssJs.style([
        CssJs.color(color),
        CssJs.margin("zero"),
        CssJs.lineHeight({
              NAME: "percent",
              VAL: 90
            }),
        CssJs.fontSize(Theme.FontSize.sm)
      ]);
  return React.createElement(AncestorCustom.Config.Base.make, {
              tag: tag,
              className: titleStyles + " " + className,
              children: Render.s(children)
            });
}

var Body = {
  make: Text$Body
};

function Text$Small(Props) {
  var colorOpt = Props.color;
  var classNameOpt = Props.className;
  var tagOpt = Props.tag;
  var children = Props.children;
  var color = colorOpt !== undefined ? colorOpt : Theme.Colors.danger;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var tag = tagOpt !== undefined ? tagOpt : "p";
  var titleStyles = CssJs.style([
        CssJs.color(color),
        CssJs.margin("zero"),
        CssJs.fontSize(Theme.FontSize.xs)
      ]);
  return React.createElement(AncestorCustom.Config.Base.make, {
              tag: tag,
              className: titleStyles + " " + className,
              children: Render.s(children)
            });
}

var Small = {
  make: Text$Small
};

function Text$Button(Props) {
  var colorOpt = Props.color;
  var classNameOpt = Props.className;
  var tagOpt = Props.tag;
  var children = Props.children;
  var color = colorOpt !== undefined ? colorOpt : Theme.Colors.white;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var tag = tagOpt !== undefined ? tagOpt : "p";
  var titleStyles = CssJs.style([
        CssJs.color(color),
        CssJs.margin("zero"),
        CssJs.unsafe("fontWeight", "bold"),
        CssJs.fontSize(Theme.FontSize.sm)
      ]);
  return React.createElement(AncestorCustom.Config.Base.make, {
              tag: tag,
              className: titleStyles + " " + className,
              children: children
            });
}

var Button = {
  make: Text$Button
};

exports.Title = Title;
exports.H3 = H3;
exports.Body = Body;
exports.Small = Small;
exports.Button = Button;
/* CssJs Not a pure module */
