// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var AncestorCustom = require("./AncestorCustom.bs.js");

var Size = {
  xs: 1,
  sm: 2,
  md: 3,
  lg: 4
};

var FontSize__xs = "10px";

var FontSize__sm = "16px";

var FontSize__md = "24px";

var FontSize__lg = "64px";

var FontSize = {
  xs: 10,
  sm: 16,
  md: 24,
  lg: 64,
  _xs: FontSize__xs,
  _sm: FontSize__sm,
  _md: FontSize__md,
  _lg: FontSize__lg
};

var xs = Curry._1(AncestorCustom.Config.Styles.Spacing.make, 1);

var sm = Curry._1(AncestorCustom.Config.Styles.Spacing.make, 2);

var md = Curry._1(AncestorCustom.Config.Styles.Spacing.make, 3);

var lg = Curry._1(AncestorCustom.Config.Styles.Spacing.make, 4);

var Padding = {
  xs: xs,
  sm: sm,
  md: md,
  lg: lg
};

var Colors = {
  primaryDark: "#5820CF",
  primary: "#743AF0",
  primaryLight: "#6F5A9A",
  successDark: "#215432",
  success: "#00A985",
  successLight: "#62836A",
  dangerDark: "#B70021",
  danger: "#FF1B51",
  dangerLight: "#DB0038",
  noneDark: "#3A3939",
  none: "#5D5C5C",
  noneLight: "#838282",
  black: "#070707",
  grayDark: "#242424",
  gray: "#3A3939",
  grayLight: "#A7A7A7",
  white: "#FFFFFF"
};

var fontFamily = "'Roboto Mono', monospace";

exports.Size = Size;
exports.FontSize = FontSize;
exports.Padding = Padding;
exports.Colors = Colors;
exports.fontFamily = fontFamily;
/* xs Not a pure module */
