// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var xs = {
  NAME: "rem",
  VAL: 1
};

var sm = {
  NAME: "rem",
  VAL: 2
};

var md = {
  NAME: "rem",
  VAL: 3
};

var lg = {
  NAME: "rem",
  VAL: 4
};

var Size = {
  xs: xs,
  sm: sm,
  md: md,
  lg: lg,
  _xs: 1,
  _sm: 2,
  _md: 3,
  _lg: 4
};

var FontSize_xs = {
  NAME: "px",
  VAL: 10
};

var FontSize_sm = {
  NAME: "px",
  VAL: 16
};

var FontSize_md = {
  NAME: "px",
  VAL: 24
};

var FontSize_lg = {
  NAME: "px",
  VAL: 64
};

var FontSize = {
  xs: FontSize_xs,
  sm: FontSize_sm,
  md: FontSize_md,
  lg: FontSize_lg
};

var Padding = {
  xs: xs,
  sm: sm,
  md: md,
  lg: lg
};

var BorderRadius_xs = {
  NAME: "rem",
  VAL: 0.4
};

var BorderRadius_sm = {
  NAME: "rem",
  VAL: 0.6
};

var BorderRadius = {
  xs: BorderRadius_xs,
  sm: BorderRadius_sm
};

var Colors_primaryDark = {
  NAME: "hex",
  VAL: "5820CF"
};

var Colors_primary = {
  NAME: "hex",
  VAL: "743AF0"
};

var Colors_primaryLight = {
  NAME: "hex",
  VAL: "6F5A9A"
};

var Colors_successDark = {
  NAME: "hex",
  VAL: "215432"
};

var Colors_success = {
  NAME: "hex",
  VAL: "00A985"
};

var Colors_successLight = {
  NAME: "hex",
  VAL: "62836A"
};

var Colors_dangerDark = {
  NAME: "hex",
  VAL: "B70021"
};

var Colors_danger = {
  NAME: "hex",
  VAL: "FF1B51"
};

var Colors_dangerLight = {
  NAME: "hex",
  VAL: "DB0038"
};

var Colors_noneDark = {
  NAME: "hex",
  VAL: "3A3939"
};

var Colors_none = {
  NAME: "hex",
  VAL: "5D5C5C"
};

var Colors_noneLight = {
  NAME: "hex",
  VAL: "838282"
};

var Colors_black = {
  NAME: "hex",
  VAL: "070707"
};

var Colors_grayDark = {
  NAME: "hex",
  VAL: "242424"
};

var Colors_grayLight = {
  NAME: "hex",
  VAL: "A7A7A7"
};

var Colors_white = {
  NAME: "hex",
  VAL: "FFFFFF"
};

var Colors_gray = {
  NAME: "hex",
  VAL: "3A3939"
};

var Colors = {
  primaryDark: Colors_primaryDark,
  primary: Colors_primary,
  primaryLight: Colors_primaryLight,
  successDark: Colors_successDark,
  success: Colors_success,
  successLight: Colors_successLight,
  dangerDark: Colors_dangerDark,
  danger: Colors_danger,
  dangerLight: Colors_dangerLight,
  noneDark: Colors_noneDark,
  none: Colors_none,
  noneLight: Colors_noneLight,
  black: Colors_black,
  grayDark: Colors_grayDark,
  grayLight: Colors_grayLight,
  white: Colors_white,
  gray: Colors_gray
};

exports.Size = Size;
exports.FontSize = FontSize;
exports.Padding = Padding;
exports.BorderRadius = BorderRadius;
exports.Colors = Colors;
/* No side effect */
