// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Req = {};

var Res = {};

var GetServerSideProps = {
  Req: Req,
  Res: Res
};

var GetStaticProps = {};

var GetStaticPaths = {};

var Link = {};

var Events = {};

var Router = {
  Events: Events
};

var $$Image = {};

var Head = {};

var $$Error = {};

var Req$1 = {};

var CtxOrReq = {
  Req: Req$1
};

var SessionProvider = {};

var Auth = {
  CtxOrReq: CtxOrReq,
  SessionProvider: SessionProvider
};

exports.GetServerSideProps = GetServerSideProps;
exports.GetStaticProps = GetStaticProps;
exports.GetStaticPaths = GetStaticPaths;
exports.Link = Link;
exports.Router = Router;
exports.$$Image = $$Image;
exports.Head = Head;
exports.$$Error = $$Error;
exports.Auth = Auth;
/* No side effect */
