// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Theme = require("../../lib/Theme/Theme.bs.js");
var React = require("react");
var Css = require("@emotion/css");
var AncestorCustom = require("../../lib/Theme/AncestorCustom.bs.js");

var container = Css.css({
      height: "100vh",
      width: "100vw",
      display: "grid",
      backgroundColor: Theme.Colors.grayDark,
      gridTemplateColumns: Curry._1(AncestorCustom.Config.Styles.Spacing.make, 6) + " auto"
    });

function Layout(Props) {
  var children = Props.children;
  return React.createElement(AncestorCustom.Config.Base.make, {
              tag: "main",
              className: container,
              children: children
            });
}

var make = Layout;

exports.container = container;
exports.make = make;
/* container Not a pure module */
