// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Theme = require("../../lib/Theme/Theme.bs.js");
var React = require("react");
var Caml_option = require("rescript/lib/js/caml_option.js");

var deleteProp = ((newProps, key) => delete newProps[key]);

function getOrEmpty(str) {
  if (str !== undefined) {
    return " " + str;
  } else {
    return "";
  }
}

var styles = CssJs.style([
      CssJs.label("Container"),
      CssJs.height({
            NAME: "vh",
            VAL: 100
          }),
      CssJs.width({
            NAME: "vw",
            VAL: 100
          }),
      CssJs.display("grid"),
      CssJs.backgroundColor(Theme.Colors.grayDark),
      CssJs.unsafe("gridTemplateColumns", "6rem auto")
    ]);

function make(props) {
  var className = styles + getOrEmpty(Caml_option.undefined_to_opt(props.className));
  var stylesObject = {
    className: className,
    ref: Caml_option.undefined_to_opt(props.innerRef)
  };
  var newProps = Object.assign({}, props, stylesObject);
  deleteProp(newProps, "innerRef");
  return React.createElement("main", newProps);
}

var Container = {
  deleteProp: deleteProp,
  getOrEmpty: getOrEmpty,
  styles: styles,
  make: make
};

exports.Container = Container;
exports.deleteProp = deleteProp;
exports.getOrEmpty = getOrEmpty;
exports.styles = styles;
exports.make = make;
/* styles Not a pure module */
