// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Theme = require("../../lib/Theme/Theme.bs.js");
var React = require("react");
var Css = require("@emotion/css");
var AncestorCustom = require("../../lib/Theme/AncestorCustom.bs.js");

var card = Css.css({
      background: Theme.Colors.grayLight,
      borderRadius: Curry._1(AncestorCustom.Config.Styles.Radius.make, 1),
      padding: Theme.Padding.xs
    });

function Card(Props) {
  var children = Props.children;
  return React.createElement(AncestorCustom.Config.Box.make, {
              px: [AncestorCustom.xs(Theme.Size.xs)],
              children: children,
              className: card
            });
}

var make = Card;

exports.card = card;
exports.make = make;
/* card Not a pure module */
