// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var FiTerminal = {};

var FiHeart = {};

var FiUser = {};

var FiSettings = {};

var FiX = {};

exports.FiTerminal = FiTerminal;
exports.FiHeart = FiHeart;
exports.FiUser = FiUser;
exports.FiSettings = FiSettings;
exports.FiX = FiX;
/* No side effect */
