// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var React = require("react");
var Layout = require("../components/Layout/Layout.bs.js");
var Navbar = require("../components/Navbar/Navbar.bs.js");
var RelayEnv = require("../lib/RelayEnv/RelayEnv.bs.js");
var NextIntl = require("next-intl");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Router = require("next/router");
var RescriptRelay = require("rescript-relay/src/RescriptRelay.bs.js");
var React$1 = require("next-auth/react");

CssJs.$$global("html, body", [
      CssJs.width({
            NAME: "percent",
            VAL: 100
          }),
      CssJs.height({
            NAME: "percent",
            VAL: 100
          }),
      CssJs.padding("zero"),
      CssJs.margin("zero")
    ]);

CssJs.$$global("*", [
      CssJs.boxSizing("borderBox"),
      CssJs.fontSize({
            NAME: "pxFloat",
            VAL: 10
          }),
      CssJs.unsafe("fontFamily", "'Roboto Mono', monospace")
    ]);

function $$default(param) {
  var pageProps = param.pageProps;
  var content = React.createElement(param.Component, pageProps);
  var match = Router.useRouter();
  var locale = match.locale;
  var messages = require("../../lang/" + String(locale) + ".json");
  return React.createElement(NextIntl.NextIntlProvider, {
              locale: locale,
              messages: messages,
              children: React.createElement(RescriptRelay.Context.Provider.make, {
                    environment: RelayEnv.createEnvironment(Caml_option.some(pageProps.records), undefined),
                    children: React.createElement(React$1.SessionProvider, {
                          session: pageProps.session,
                          children: React.createElement(Layout.make, {
                                children: null
                              }, React.createElement(Navbar.make, {}), React.createElement("section", undefined, content))
                        })
                  })
            });
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/*  Not a pure module */
