// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Render = require("../lib/Render/Render.bs.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var RescriptRelay = require("rescript-relay/src/RescriptRelay.bs.js");
var RelayRuntime = require("relay-runtime");
var AncestorCustom = require("../lib/Theme/AncestorCustom.bs.js");
var React$1 = require("next-auth/react");
var Hooks = require("react-relay/hooks");
var ReviewQuery_graphql = require("../__generated__/rescript-relay/ReviewQuery_graphql.bs.js");
var RescriptRelay_Internal = require("rescript-relay/src/RescriptRelay_Internal.bs.js");

function use(variables, fetchPolicy, fetchKey, networkCacheConfig, param) {
  var data = Hooks.useLazyLoadQuery(ReviewQuery_graphql.node, RescriptRelay_Internal.internal_cleanObjectFromUndefinedRaw(ReviewQuery_graphql.Internal.convertVariables(variables)), {
        fetchKey: fetchKey,
        fetchPolicy: RescriptRelay.mapFetchPolicy(fetchPolicy),
        networkCacheConfig: networkCacheConfig
      });
  return RescriptRelay_Internal.internal_useConvertedValue(ReviewQuery_graphql.Internal.convertResponse, data);
}

function useLoader(param) {
  var match = Hooks.useQueryLoader(ReviewQuery_graphql.node);
  var loadQueryFn = match[1];
  var loadQuery = React.useMemo((function () {
          return function (param, param$1, param$2, param$3) {
            return Curry._2(loadQueryFn, ReviewQuery_graphql.Internal.convertVariables(param), {
                        fetchPolicy: param$1,
                        networkCacheConfig: param$2
                      });
          };
        }), [loadQueryFn]);
  return [
          Caml_option.nullable_to_opt(match[0]),
          loadQuery,
          match[2]
        ];
}

function $$fetch(environment, variables, onResult, networkCacheConfig, fetchPolicy, param) {
  Hooks.fetchQuery(environment, ReviewQuery_graphql.node, ReviewQuery_graphql.Internal.convertVariables(variables), {
          networkCacheConfig: networkCacheConfig,
          fetchPolicy: RescriptRelay.mapFetchQueryFetchPolicy(fetchPolicy)
        }).subscribe({
        next: (function (res) {
            return Curry._1(onResult, {
                        TAG: /* Ok */0,
                        _0: ReviewQuery_graphql.Internal.convertResponse(res)
                      });
          }),
        error: (function (err) {
            return Curry._1(onResult, {
                        TAG: /* Error */1,
                        _0: err
                      });
          })
      });
  
}

function fetchPromised(environment, variables, networkCacheConfig, fetchPolicy, param) {
  var __x = Hooks.fetchQuery(environment, ReviewQuery_graphql.node, ReviewQuery_graphql.Internal.convertVariables(variables), {
          networkCacheConfig: networkCacheConfig,
          fetchPolicy: RescriptRelay.mapFetchQueryFetchPolicy(fetchPolicy)
        }).toPromise();
  return __x.then(function (res) {
              return Promise.resolve(ReviewQuery_graphql.Internal.convertResponse(res));
            });
}

function usePreloaded(queryRef, param) {
  var data = Hooks.usePreloadedQuery(ReviewQuery_graphql.node, queryRef);
  return RescriptRelay_Internal.internal_useConvertedValue(ReviewQuery_graphql.Internal.convertResponse, data);
}

function retain(environment, variables) {
  var operationDescriptor = RelayRuntime.createOperationDescriptor(ReviewQuery_graphql.node, ReviewQuery_graphql.Internal.convertVariables(variables));
  return environment.retain(operationDescriptor);
}

var Query = {
  Types: undefined,
  use: use,
  useLoader: useLoader,
  $$fetch: $$fetch,
  fetchPromised: fetchPromised,
  usePreloaded: usePreloaded,
  retain: retain
};

function Review$Decks(Props) {
  var queryData = use(undefined, undefined, undefined, undefined, undefined);
  console.log(queryData.posts);
  return Render.map(queryData.posts, (function (thisDeck) {
                return React.createElement("div", {
                            key: thisDeck.id
                          }, Render.s(thisDeck.title));
              }));
}

var Decks = {
  make: Review$Decks
};

function $$default(param) {
  return React.createElement(AncestorCustom.Config.Box.make, {
              children: React.createElement(React.Suspense, {
                    children: React.createElement(Review$Decks, {}),
                    fallback: "Loading...."
                  })
            });
}

function getServerSideProps(ctx) {
  return React$1.getSession(ctx).then(function (session) {
              return Promise.resolve({
                          props: {
                            fromServer: session
                          }
                        });
            });
}

exports.Query = Query;
exports.Decks = Decks;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.getServerSideProps = getServerSideProps;
/* react Not a pure module */
