// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var AncestorCustom = require("../lib/Theme/AncestorCustom.bs.js");
var React$1 = require("next-auth/react");

function Review$Decks(Props) {
  return null;
}

var Decks = {
  make: Review$Decks
};

function $$default(param) {
  return React.createElement(AncestorCustom.Config.Box.make, {
              children: React.createElement(React.Suspense, {
                    children: React.createElement(Review$Decks, {}),
                    fallback: "Loading...."
                  })
            });
}

function getServerSideProps(ctx) {
  return React$1.getSession(ctx).then(function (session) {
              return Promise.resolve({
                          props: {
                            fromServer: session
                          }
                        });
            });
}

exports.Decks = Decks;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.getServerSideProps = getServerSideProps;
/* react Not a pure module */
