// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Theme = require("../../lib/Theme/Theme.bs.js");
var Css = require("@emotion/css");
var AncestorCustom = require("../../lib/Theme/AncestorCustom.bs.js");

var container = Css.css({
      backgroundColor: Theme.Colors.gray,
      width: "100%",
      height: "100%",
      display: "flex",
      flexDirection: "column"
    });

function icon(activeOpt, pushToBottomOpt, param) {
  var active = activeOpt !== undefined ? activeOpt : false;
  var pushToBottom = pushToBottomOpt !== undefined ? pushToBottomOpt : false;
  return Css.css({
              padding: Theme.Padding.xs,
              position: "relative",
              "svg, img": {
                width: Curry._1(AncestorCustom.Config.Styles.Spacing.make, 4),
                height: Curry._1(AncestorCustom.Config.Styles.Spacing.make, 4)
              },
              marginTop: pushToBottom ? "auto" : "unset",
              color: Theme.Colors.grayLight,
              cursor: "pointer",
              "&:hover": {
                color: Theme.Colors.white
              },
              "&:before": {
                content: "' '",
                height: Curry._1(AncestorCustom.Config.Styles.Spacing.make, 6),
                width: "2px",
                position: "absolute",
                top: "0",
                left: "0",
                backgroundColor: Theme.Colors.white,
                display: active ? "unset" : "none"
              }
            });
}

exports.container = container;
exports.icon = icon;
/* container Not a pure module */
