// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Theme = require("../../lib/Theme/Theme.bs.js");
var React = require("react");
var NextIntl = require("../../bindings/NextIntl/NextIntl.bs.js");
var Link = require("next/link").default;
var Caml_option = require("rescript/lib/js/caml_option.js");
var Router = require("next/router");
var Css = require("@emotion/css");
var AncestorCustom = require("../../lib/Theme/AncestorCustom.bs.js");
var React$1 = require("next-auth/react");
var Feather = require("@emotion-icons/feather");

var container = Css.css({
      backgroundColor: Theme.Colors.gray,
      width: "100%",
      height: "100%",
      display: "flex",
      flexDirection: "column"
    });

function icon(activeOpt, pushToBottomOpt, param) {
  var active = activeOpt !== undefined ? activeOpt : false;
  var pushToBottom = pushToBottomOpt !== undefined ? pushToBottomOpt : false;
  return Css.css({
              padding: Theme.Padding.xs,
              position: "relative",
              "svg, img": {
                width: Curry._1(AncestorCustom.Config.Styles.Spacing.make, 4),
                height: Curry._1(AncestorCustom.Config.Styles.Spacing.make, 4)
              },
              marginTop: pushToBottom ? "auto" : "unset",
              color: Theme.Colors.grayLight,
              cursor: "pointer",
              "&:hover": {
                color: Theme.Colors.white
              },
              "&:before": {
                content: "' '",
                height: Curry._1(AncestorCustom.Config.Styles.Spacing.make, 6),
                width: "2px",
                position: "absolute",
                top: "0",
                left: "0",
                backgroundColor: Theme.Colors.white,
                display: active ? "unset" : "none"
              }
            });
}

var Styles = {
  container: container,
  icon: icon
};

function Navbar$NavItem(Props) {
  var href = Props.href;
  var icon$1 = Props.icon;
  var title = Props.title;
  var activeOpt = Props.active;
  var pushToBottomOpt = Props.pushToBottom;
  var onClick = Props.onClick;
  var active = activeOpt !== undefined ? activeOpt : false;
  var pushToBottom = pushToBottomOpt !== undefined ? pushToBottomOpt : false;
  var content = href !== undefined ? React.createElement(Link, {
          href: href,
          children: React.createElement("div", undefined, icon$1)
        }) : icon$1;
  var tmp = {
    children: content,
    className: icon(active, pushToBottom, undefined),
    ariaSelected: active
  };
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  if (title !== undefined) {
    tmp.title = Caml_option.valFromOption(title);
  }
  return React.createElement(AncestorCustom.Config.Box.make, tmp);
}

var NavItem = {
  make: Navbar$NavItem
};

function Navbar(Props) {
  var match = Router.useRouter();
  var pathname = match.pathname;
  var session = React$1.useSession();
  var t = NextIntl.useTranslations(undefined);
  var match$1 = session.data;
  var tmp;
  if (match$1 == null) {
    tmp = React.createElement(Feather.User, {});
  } else {
    var user = match$1.user;
    tmp = React.createElement(AncestorCustom.Config.Base.make, {
          tag: "img",
          alt: user.name,
          src: user.image
        });
  }
  return React.createElement(AncestorCustom.Config.Box.make, {
              children: null,
              className: container
            }, React.createElement(Navbar$NavItem, {
                  href: "/",
                  icon: React.createElement(Feather.Terminal, {}),
                  title: Curry._1(t, "Code"),
                  active: pathname === "/"
                }), React.createElement(Navbar$NavItem, {
                  href: "/review",
                  icon: React.createElement(Feather.Heart, {}),
                  title: Curry._1(t, "Review"),
                  active: pathname === "/review"
                }), React.createElement(Navbar$NavItem, {
                  icon: tmp,
                  title: Curry._1(t, (session.data == null) ? "Signin" : "Signout"),
                  pushToBottom: true,
                  onClick: (session.data == null) ? (function (prim) {
                        React$1.signIn(prim);
                        
                      }) : (function (prim) {
                        React$1.signOut(prim);
                        
                      })
                }), React.createElement(Navbar$NavItem, {
                  icon: React.createElement(Feather.Settings, {}),
                  title: Curry._1(t, "Settings")
                }));
}

var make = Navbar;

exports.Styles = Styles;
exports.NavItem = NavItem;
exports.make = make;
/* container Not a pure module */
