// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var NextIntl = require("../../bindings/NextIntl/NextIntl.bs.js");
var Link = require("next/link").default;
var Caml_option = require("rescript/lib/js/caml_option.js");
var Router = require("next/router");
var Navbar_Styles = require("./Navbar_Styles.bs.js");
var AncestorCustom = require("../../lib/Theme/AncestorCustom.bs.js");
var React$1 = require("next-auth/react");
var Feather = require("@emotion-icons/feather");

function Navbar$NavItem(Props) {
  var href = Props.href;
  var icon = Props.icon;
  var title = Props.title;
  var activeOpt = Props.active;
  var pushToBottomOpt = Props.pushToBottom;
  var onClick = Props.onClick;
  var active = activeOpt !== undefined ? activeOpt : false;
  var pushToBottom = pushToBottomOpt !== undefined ? pushToBottomOpt : false;
  var content = href !== undefined ? React.createElement(Link, {
          href: href,
          children: React.createElement("div", undefined, icon)
        }) : icon;
  var tmp = {
    children: content,
    className: Navbar_Styles.icon(active, pushToBottom, undefined),
    ariaSelected: active
  };
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  if (title !== undefined) {
    tmp.title = Caml_option.valFromOption(title);
  }
  return React.createElement(AncestorCustom.Config.Box.make, tmp);
}

var NavItem = {
  make: Navbar$NavItem
};

function Navbar(Props) {
  var match = Router.useRouter();
  var pathname = match.pathname;
  var session = React$1.useSession();
  var t = NextIntl.useTranslations(undefined);
  var match$1 = session.data;
  var tmp;
  if (match$1 == null) {
    tmp = React.createElement(Feather.User, {});
  } else {
    var user = match$1.user;
    tmp = React.createElement(AncestorCustom.Config.Base.make, {
          tag: "img",
          alt: user.name,
          src: user.image
        });
  }
  return React.createElement(AncestorCustom.Config.Box.make, {
              children: null,
              className: Navbar_Styles.container
            }, React.createElement(Navbar$NavItem, {
                  href: "/",
                  icon: React.createElement(Feather.Terminal, {}),
                  title: Curry._1(t, "Posts"),
                  active: pathname === "/"
                }), React.createElement(Navbar$NavItem, {
                  href: "/review",
                  icon: React.createElement(Feather.Heart, {}),
                  title: Curry._1(t, "Review"),
                  active: pathname === "/review"
                }), React.createElement(Navbar$NavItem, {
                  icon: tmp,
                  title: Curry._1(t, (session.data == null) ? "Signin" : "Signout"),
                  pushToBottom: true,
                  onClick: (session.data == null) ? (function (prim) {
                        React$1.signIn(prim);
                        
                      }) : (function (prim) {
                        React$1.signOut(prim);
                        
                      })
                }), React.createElement(Navbar$NavItem, {
                  icon: React.createElement(Feather.Settings, {}),
                  title: Curry._1(t, "Settings")
                }));
}

var Styles;

var make = Navbar;

exports.Styles = Styles;
exports.NavItem = NavItem;
exports.make = make;
/* react Not a pure module */
