"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertTagArgs = exports.UpdateTagArgs = exports.UpdateManyTagArgs = exports.GroupByTagArgs = exports.FindUniqueTagArgs = exports.FindManyTagArgs = exports.FindFirstTagArgs = exports.DeleteTagArgs = exports.DeleteManyTagArgs = exports.CreateTagArgs = exports.CreateManyTagArgs = exports.AggregateTagArgs = void 0;
var AggregateTagArgs_1 = require("./AggregateTagArgs");
Object.defineProperty(exports, "AggregateTagArgs", { enumerable: true, get: function () { return AggregateTagArgs_1.AggregateTagArgs; } });
var CreateManyTagArgs_1 = require("./CreateManyTagArgs");
Object.defineProperty(exports, "CreateManyTagArgs", { enumerable: true, get: function () { return CreateManyTagArgs_1.CreateManyTagArgs; } });
var CreateTagArgs_1 = require("./CreateTagArgs");
Object.defineProperty(exports, "CreateTagArgs", { enumerable: true, get: function () { return CreateTagArgs_1.CreateTagArgs; } });
var DeleteManyTagArgs_1 = require("./DeleteManyTagArgs");
Object.defineProperty(exports, "DeleteManyTagArgs", { enumerable: true, get: function () { return DeleteManyTagArgs_1.DeleteManyTagArgs; } });
var DeleteTagArgs_1 = require("./DeleteTagArgs");
Object.defineProperty(exports, "DeleteTagArgs", { enumerable: true, get: function () { return DeleteTagArgs_1.DeleteTagArgs; } });
var FindFirstTagArgs_1 = require("./FindFirstTagArgs");
Object.defineProperty(exports, "FindFirstTagArgs", { enumerable: true, get: function () { return FindFirstTagArgs_1.FindFirstTagArgs; } });
var FindManyTagArgs_1 = require("./FindManyTagArgs");
Object.defineProperty(exports, "FindManyTagArgs", { enumerable: true, get: function () { return FindManyTagArgs_1.FindManyTagArgs; } });
var FindUniqueTagArgs_1 = require("./FindUniqueTagArgs");
Object.defineProperty(exports, "FindUniqueTagArgs", { enumerable: true, get: function () { return FindUniqueTagArgs_1.FindUniqueTagArgs; } });
var GroupByTagArgs_1 = require("./GroupByTagArgs");
Object.defineProperty(exports, "GroupByTagArgs", { enumerable: true, get: function () { return GroupByTagArgs_1.GroupByTagArgs; } });
var UpdateManyTagArgs_1 = require("./UpdateManyTagArgs");
Object.defineProperty(exports, "UpdateManyTagArgs", { enumerable: true, get: function () { return UpdateManyTagArgs_1.UpdateManyTagArgs; } });
var UpdateTagArgs_1 = require("./UpdateTagArgs");
Object.defineProperty(exports, "UpdateTagArgs", { enumerable: true, get: function () { return UpdateTagArgs_1.UpdateTagArgs; } });
var UpsertTagArgs_1 = require("./UpsertTagArgs");
Object.defineProperty(exports, "UpsertTagArgs", { enumerable: true, get: function () { return UpsertTagArgs_1.UpsertTagArgs; } });
