// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var NextIntl = require("next-intl");

var NextIntlProvider = {};

var Trans = {};

function useTranslations(param) {
  var intl = NextIntl.useTranslations();
  return function (message) {
    return intl(message);
  };
}

function useTranslationsWithValues(param) {
  var intl = NextIntl.useTranslations();
  return function (message, values) {
    return intl(message, values);
  };
}

exports.NextIntlProvider = NextIntlProvider;
exports.Trans = Trans;
exports.useTranslations = useTranslations;
exports.useTranslationsWithValues = useTranslationsWithValues;
/* next-intl Not a pure module */
